version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=squares;Username=postgres;Password=kinderevicius111

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kinderevicius111
      POSTGRES_DB: squares
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
